# Generated by Django 5.1.7 on 2025-04-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_alter_post_options_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='counted_views',
        ),
        migrations.AddField(
            model_name='post',
            name='counted_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
